### ISSUE TITLE
Deleting tailnet key: unexpected EOF

### ISSUE THREAD

**Issue by lincolnmantracer** [davidsbond/terraform-provider-tailscale#113]
I just tried to recreate a tailnet key using terraform. My config is something like:

```
resource "time_rotating" "tskey" {
  rotation_minutes = 5
}

resource "tailscale_tailnet_key" "tskey" {
  reusable      = true
  preauthorized = true

  lifecycle {
    replace_triggered_by = [time_rotating.tskey]
  }
}
```

(Just testing rotation, natch.)

The rotation successfully triggered a replace, but that showed an error:

```
tailscale_tailnet_key.tskey: Destroying... [id=k.....CNTRL]
╷
│ Error: Failed to delete key
│
│ hujson: line 1, column 1: parsing value: unexpected EOF
```

Now `plan` is showing a 404 for that resource - so I guess the delete succeeded, but it isn't updating the state correctly?

```
tailscale_tailnet_key.tskey: Refreshing state... [id=k......CNTRL]
╷
│ Error: Failed to fetch key
│
│   with tailscale_tailnet_key.tskey,
│   on main.tf line 35, in resource "tailscale_tailnet_key" "tskey":
│   35: resource "tailscale_tailnet_key" "tskey" {
│
│ 404 page not found (404)
```

`state rm tailscale_tailnet_key.tskey` fixed it, and I was able to create the new key.

**Comment by davidsbond** [comment]
Hey @lincolnmantracer, based on the `EOF` error and `404 page not found (404)`, seems like something strange is going on that's causing the API request to go somewhere they shouldn't. I'll have a go a replicating this locally and see what I can find. 

Does the same error occur when you try to delete a tailnet key by just removing the resource? Rather than using the time rotation?

**Comment by lincolnmantracer** [comment]
I can check that, but in the meantime, I also got the 404 by using a single-use key. Running `plan` again after the key had been used (and disappeared) triggered it.

**Comment by davidsbond** [comment]
I suspect the issue has come from #102. That API request returns an empty response body based on [the docs](https://github.com/tailscale/tailscale/blob/main/api.md#delete-apiv2tailnettailnetkeyskeyid---delete-a-specific-key), so I think it's trying to parse an empty response and failing.

What happens next is that the key has been successfully deleted, but the state isn't updated due to that `EOF` error. Then when you subsequently plan it can't find that key because it has been deleted. I'll do a test to confirm that. 

Should just be a small change in the client package to handle empty responses if I'm correct.

**Comment by davidsbond** [comment]
@lincolnmantracer, the CI for v0.11.1 is running now, give it some time and that new version should be available in the terraform registry. Please give it a try and let me know if your issue persists.

**Comment by lincolnmantracer** [comment]
Looks fixed on my end! Thank you!
