### ISSUE TITLE
Creating an ACL with `ssh` fails silently and disables ssh

### ISSUE THREAD

**Issue by lincolnmantracer** [davidsbond/terraform-provider-tailscale#121]
I am using `tailscale_acl` to update the ACL:

```terraform
resource "tailscale_acl" "default" {
  acl = jsonencode({
    groups = {
      "group:dev" = [
        "person@example.com",
      ],
    },
   ...
    ssh = [
      {
        action = "accept",
        src    = ["group:dev"],
        dst    = ["tag:foo"],
        users  = ["autogroup:nonroot"]
      }
    ]
  })
}
```

When I `apply`, the ssh config is missing from the ACL at https://login.tailscale.com/admin/acls and the `enable ssh` button reappears. If I click `enable ssh` and try to re-apply, it doesn't even notice that the config has changed and needs to be updated (even though tailscale added the default ssh config).

Pretty sure this must be an upstream bug, but wanted to raise it here first.

**Comment by davidsbond** [comment]
Hey @lincolnmantracer, I [recently did an update](https://github.com/davidsbond/tailscale-client-go/commit/c5c40c9b1caa1068ba5c9acce4caf29adbceaea7) to support the SSH clause in this provider but neglected to release a new version. So what is happening here is when the ACL is loaded into memory by the provider it does not include the "ssh" section when shipping it off to the Tailscale API.

I've just triggered a release of 0.12.0 which should allow you to include the ssh section. 

Give that version a go and let me know if everything works as you expect.

**Comment by lincolnmantracer** [comment]
Gotcha, will try it tomorrow, thanks! Maybe it's worth throwing an error on unrecognized fields, maybe using [`DisallowUnusedFields`](https://pkg.go.dev/encoding/json#Decoder.DisallowUnknownFields)?

**Comment by davidsbond** [comment]
Yeah, that could be a suitable usage, to at least throw an error so people know why ACL sections might disappear if they aren't supported yet. 

The reasoning behind ACLs working this way in the provider is mostly due to the nature of checking against the upstream state. Comparing the string version of your local ACL and the upstream ACL is likely to be inaccurate due to things like whitespace and formatting done by the Tailscale API on ingest. So in this provider we use structs representing the ACL which are much easier to compare. This unfortunately means that you get these silent failures when the ACL structs haven't been updated to include new sections. 

It's definitely not the best UX so I'll have a think about a way to surface this.

**Comment by rojomisin** [comment]
which keys are supported in the tailscale_acl resource?  I'm trying to use groups, hosts and acls
