### ISSUE TITLE
Can you give an example of what the domain looks like?

### ISSUE THREAD

**Issue by tomjohnburton** [davidsbond/terraform-provider-tailscale#18]
I keep getting `unknown tailnet` error

**Comment by tomjohnburton** [comment]
Ah I worked it out. Perhaps update the documentation to say.

The domain you signed up to Tailscale with. This is found by clicking on your avatar in the top right of the screen. For a while I thought it was the `tailscale` api domain.

Thanks for creating this. Let me know how I can contribute 👍🏻

**Comment by davidsbond** [comment]
Hey @tomjohnburton, this is described in the Tailscale documentation, it's actually I question I asked them myself when I started making this provider. Glad you figured it out. 

If you want, you can add the explanation to the documentation here for the `tailnet` field:

https://github.com/davidsbond/terraform-provider-tailscale/blob/master/docs/index.md

Otherwise, you can find the answer in the tailscale documentation for Magic DNS:

https://tailscale.com/kb/1081/magic-dns/ (See Full domain names vs. machine names)

and in their API documentation:

https://github.com/tailscale/tailscale/blob/main/api.md#tailnet (See Tailnet)
